### ISSUE TITLE
Integrate the audio processors in the global navigation layout

### ISSUE THREAD

**Issue by vincentcourtois** [modular-synthesizer/frontend#61]
## Needs

As an _administrator_  
I want to be able to _have a way to easily access the list of audio processors_  
So that I can _start adding new ones and listing existing ones_

**Comment by babausse** [comment]
## Notes

* This could mean "rework the administration page to have separate ones for each resource type and have a dropdown menu on the administration menu item to access it"

**Comment by vincentcourtois** [comment]
Processors are now bundled as a side project into one single JavaScript file.
