### ISSUE TITLE
Use a differenciation key for the different localstorage depending on the environment

### ISSUE THREAD

**Issue by vincentcourtois** [modular-synthesizer/frontend#76]
## Context

* The development environment is currently correctly deployed
* The https://synple.app/ and https://synple.app/dev/ are on the same domain
* They share the same local storage
* They should not be sharing it as it disallow to be logged on one and not the other, or to have different sessions/accounts on one another

## Needs

As a _user accessing the production and development environment_. 
I want to be able to _differenciate both environments to not share informations between them_. 
So that I can _make different operations on different data in both environment easily_

**Comment by babausse** [comment]
## Notes

One way to deal with it would be to have a centralized localstorage service that access data by prepending a prefix to the keys depending on the environment name (`dev` or `prod` for example) so that even if everything is stored in the same local storage, it's accessed differently

**Comment by vincentcourtois** [comment]
No need anymore.
